<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUHQhFFl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUHQhFFl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUHQhFFl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUHQhFFl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUHQhFFl\App_KernelDevDebugContainer([
    'container.build_hash' => 'UHQhFFl',
    'container.build_id' => 'd13a0f87',
    'container.build_time' => 1631174951,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUHQhFFl');
