<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX1y9g4Z\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX1y9g4Z/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX1y9g4Z.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX1y9g4Z\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX1y9g4Z\App_KernelDevDebugContainer([
    'container.build_hash' => 'X1y9g4Z',
    'container.build_id' => 'a4aa3534',
    'container.build_time' => 1631526141,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX1y9g4Z');
